SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tii_ticketInfo] (
		[UNID]                               [int] IDENTITY(1, 1) NOT FOR REPLICATION NOT NULL,
		[ti_ticket_UNID]                     [int] NULL,
		[atl_artikel_UNID]                   [varchar](20) COLLATE Latin1_General_CI_AS NULL,
		[lv_leistungsverzeichnis_UNID]       [int] NULL,
		[lv_variante]                        [varchar](200) COLLATE Latin1_General_CI_AS NULL,
		[cs1_cos1_UNID]                      [char](2) COLLATE Latin1_General_CI_AS NULL,
		[cs2_cos2_UNID]                      [char](5) COLLATE Latin1_General_CI_AS NULL,
		[cs3_cos3_UNID]                      [char](8) COLLATE Latin1_General_CI_AS NULL,
		[hsc_helioscode_unid]                [varchar](10) COLLATE Latin1_General_CI_AS NULL,
		[rg_Rabattgruppe_UNID]               [varchar](30) COLLATE Latin1_General_CI_AS NULL,
		[tii_hinterlegterrabatt]             [decimal](7, 6) NULL,
		[tii_prozentrabatt]                  [bit] NULL,
		[tii_rabatt_VI]                      [decimal](7, 6) NULL,
		[tii_rabatt_PM]                      [decimal](7, 6) NULL,
		[tii_maxrabattausrabattstruktur]     [decimal](5, 2) NULL,
		[tii_ghmarge_oder_aufschlag]         [decimal](5, 2) NULL,
		[tii_produktmanager]                 [varchar](50) COLLATE Latin1_General_CI_AS NULL,
		[tii_pmfreigabe]                     [char](1) COLLATE Latin1_General_CI_AS NULL,
		[tii_ccomarge]                       [decimal](11, 2) NULL,
		[tii_ccomarge_monetary]              [decimal](11, 2) NULL,
		[tii_localmarge]                     [decimal](11, 2) NULL,
		[tii_localmarge_monetary]            [decimal](11, 2) NULL,
		[tii_deltaae]                        [decimal](11, 2) NULL,
		[tii_delta_mitzielmarge]             [decimal](11, 2) NULL,
		[tii_ccomarge_helios_ytd]            [decimal](11, 2) NULL,
		[tii_artikelname]                    [varchar](50) COLLATE Latin1_General_CI_AS NULL,
		[tii_zielnettopreis]                 [decimal](11, 2) NULL,
		[tii_artikellistenpreis]             [decimal](11, 2) NULL,
		[tii_preiseinheit]                   [varchar](20) COLLATE Latin1_General_CI_AS NULL,
		[tii_gesamtumsatz]                   [decimal](11, 2) NULL,
		[tii_csc_wert]                       [decimal](11, 2) NULL,
		[tii_csc_einheit]                    [decimal](11, 2) NULL,
		[tii_csc_marge]                      [decimal](11, 2) NULL,
		[tii_csc_marge_monetary]             [decimal](11, 2) NULL,
		[tii_Nettopreis]                     [decimal](11, 2) NULL,
		[tii_gesamtpreisNetto]               [decimal](11, 2) NULL,
		[tii_delta_vs_target]                [decimal](11, 2) NULL,
		[tii_delta_vs_min]                   [decimal](11, 2) NULL,
		[tii_dvc_in_euro]                    [decimal](11, 2) NULL,
		[tii_stueckzahl]                     [decimal](11, 2) NULL,
		[tii_cscStueck]                      [decimal](11, 2) NULL,
		[tii_volumen]                        [decimal](11, 2) NULL,
		[tii_position_typeahead]             [varchar](100) COLLATE Latin1_General_CI_AS NULL,
		[tii_position_unid]                  [varchar](100) COLLATE Latin1_General_CI_AS NULL,
		[tii_position_typ]                   [varchar](20) COLLATE Latin1_General_CI_AS NULL,
		[tii_position_menge]                 [varchar](50) COLLATE Latin1_General_CI_AS NULL,
		[tii_bulkinsert]                     [varchar](50) COLLATE Latin1_General_CI_AS NULL,
		[tii_ebenegewaehlterrabatt]          [varchar](20) COLLATE Latin1_General_CI_AS NULL,
		[tii_optional]                       [bit] NULL,
		[tii_zusatzrabatt]                   [decimal](7, 6) NULL,
		[tii_Gesamtrabatt]                   [decimal](7, 6) NULL,
		[ddk_bild]                           [char](33) COLLATE Latin1_General_CI_AS NULL,
		[tii_gruppenname]                    [varchar](200) COLLATE Latin1_General_CI_AS NULL,
		[tii_positionsbezeichnung]           [varchar](200) COLLATE Latin1_General_CI_AS NULL,
		[tii_artikeltext]                    [varchar](300) COLLATE Latin1_General_CI_AS NULL,
		[tii_transferprice]                  [decimal](11, 2) NULL,
		[tii_standardcosts]                  [decimal](11, 2) NULL,
		[tii_kostenart]                      [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[updatedBy]                          [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[tii_gesamtrabatt_VI]                [decimal](7, 6) NULL,
		[tii_gesamtpreisnetto_VI]            [decimal](11, 2) NULL,
		[tii_gesamtrabatt_PM]                [decimal](7, 6) NULL,
		[tii_gesamtpreisnetto_PM]            [decimal](11, 2) NULL,
		[tii_rabatt_Ind]                     [decimal](7, 6) NULL,
		[tii_zusatzrabatt_Ind]               [decimal](7, 6) NULL,
		[tii_gesamtrabatt_Ind]               [decimal](7, 6) NULL,
		[tii_gesamtpreisnetto_Ind]           [decimal](11, 2) NULL,
		CONSTRAINT [tii_ticketInfo_PK]
		PRIMARY KEY
		CLUSTERED
		([UNID])
	ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[tii_ticketInfo] SET (LOCK_ESCALATION = TABLE)
GO
